name: generate-markdown
on:
  push:
    branches: $default-branch
    paths:
      - 'azbuka.json'
  workflow_dispatch:
jobs:
  generate-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run makeMarkdown
      - run: npm run prettier:write
      - name: Push changes
        run: |
          git config --global user.name 'DeazbukaBot'
          git config --global user.email 'deazbuka-bot@deazbuka.github.io'
          git commit -am "[DeazbukaBot] Обновил markdown"
          git push
