name: manual-refine-azbuka
on:
  issue_comment:
    types: [created]
jobs:
  manual-refine-azbuka:
    # Запускаем, когда один из юзеров вайтлиста написал в pr комментарий по формату "#слово Слово, на которое нужно поменять последнее в azbuka.json"
    if: ${{ github.event.issue.pull_request && contains(fromJson('["KarKarbI4"]'), github.event.comment.user.login) && startsWith(github.event.comment.body, '#слово') }}
    runs-on: ubuntu-latest
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMAND_PREFIX: '#слово '
    steps:
      - name: Оповещаем о старте
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
      - uses: actions/checkout@v2
      # Способ как чекаутнуться на ветку pr из комментария взят здесь:
      # https://github.com/actions/checkout/issues/331#issuecomment-674464772
      - name: Checkout to pr branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: checkoutToPr
        run: |
          hub pr checkout ${{ github.event.issue.number }}
          echo ::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Парсим слово из комментария
        id: parseWord
        run: echo ::set-output name=word::${COMMENT_BODY#"$COMMAND_PREFIX"}
      - run: npm ci
      - run: npm run updateLatestWord -- ${{ steps.parseWord.outputs.word }}
      - run: npm run prettier:write
      - name: Обновляем pr
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          committer: DeazbukaBot <deazbuka-bot@deazbuka.github.io>
          author: DeazbukaBot <deazbuka-bot@deazbuka.github.io>
          base: main
          branch: ${{ steps.checkoutToPr.outputs.branch }}
          title: ${{ format('Добавил {0}', steps.parseWord.outputs.word) }}
          body: ${{ format('Добавил {0}', steps.parseWord.outputs.word) }}
          commit-message: ${{ format('[DeazbukaBot] Добавил {0}', steps.parseWord.outputs.word) }}
          labels: 'automerge'
          delete-branch: true
      - name: Убираем wip
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: wip
